# Generated by Django 5.2.8 on 2025-11-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('financial_goals', models.CharField(max_length=200)),
                ('account_opening_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('data_sources', models.JSONField(blank=True, default=list)),
                ('thought_signature', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.customer'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('transaction', 'Transaction Data'), ('investment', 'Investment Data'), ('customer', 'Customer Data'), ('document', 'Document')], max_length=20)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('records_imported', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='chatbot.customer')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('purchase_nav', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_nav', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('returns_absolute', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returns_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='chatbot.customer')),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['customer', 'product_type'], name='investments_custome_2bf486_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('merchant', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chatbot.customer')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'date'], name='transaction_custome_60c872_idx'), models.Index(fields=['category'], name='transaction_categor_45fcdd_idx')],
            },
        ),
    ]
